export const EMAILS = [
  {
    id: 'e0',
    from: 'Doris Li',
    email: 'doris.li@hisense.com',
    initials: 'DL',
    time: '10:14 AM',
    stamp: 'Jul 30, 2026 at 10:14:22 AM',
    confidence: 32,
    subject: 'Inbound Delivery(Monterrey->Pantos TX, Charger, G170, 7/30)',
    po: 'G170',
    ref: '7/30',
    lane: 'Monterrey → Pantos, TX',
    dept: 'CSR / Dispatch',
    intent: 'Shipment status update',
    sub: 'Multi-stop inbound · needs review',
    tier: 'Escalation',
    reason: 'Critic unsatisfied',
    body: 'Dear Team,\n\nPlease find below the inbound delivery details for Monterrey → Pantos TX (Charger, G170, 7/30).\n\nKindly confirm receipt of each unit and advise on offload / delivery appointments.\n\nThanks,\nDoris Li\nHisense Logistics',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'Hisense@chargerlogistics.com',
      'ryan@chargerlogistics.com',
      'dispatch@chargerlogistics.com',
    ],
    ccCount: 14,
    attachments: [{ name: 'Inbound_G170_0730.xlsx', size: '186 KB' }],
    table: {
      headers: [
        'Issuing Date',
        'PO Number',
        'Customer Model',
        'Trailer Number',
        'Sum of Issuing Quantity',
        'Carrier',
      ],
      rows: [
        ['7/28/2026', '6000445891', '75U8K', 'CFT-4412', '42', 'Charger'],
        ['7/28/2026', '6000445892', '65U8K', 'CFT-4412', '38', 'Charger'],
        ['7/29/2026', '6000445910', '55U7N', 'CFT-4488', '60', 'Charger'],
        ['7/29/2026', '6000445911', '50U6H', 'CFT-4488', '54', 'Charger'],
        ['7/30/2026', '6000445933', '43A6H', 'CFT-4501', '72', 'Charger'],
        ['7/30/2026', '6000445934', '32A4H', 'CFT-4501', '80', 'Charger'],
      ],
    },
    langs: ['EN'],
    tones: [
      {
        id: 'status',
        label: 'Status update',
        EN: 'Hi Doris,\n\nThanks for the inbound delivery notice for Monterrey → Pantos TX (Charger, G170, 7/30).\n\nDelivery Status Updates\n• Units on trailers CFT-4412, CFT-4488, and CFT-4501 are in transit to Pantos, TX.\n• Border crossing is planned for today; we will confirm once each unit clears.\n\nOffload Information\n• Receiving dock: Pantos TX FG\n• Please hold the appointment window until we send the final ETA after crossing.\n\nConfirmed Delivery Appointments\n• We will reply with appointment numbers for each trailer as soon as Pantos assigns them.\n\nRegards,\nCharger Logistics | CSR Team',
      },
      {
        id: 'escalate',
        label: 'Escalate + clarify',
        EN: 'Hi Doris,\n\nWe received the G170 inbound list for Pantos TX. Before we confirm appointments, we need clarification on two points:\n\n1) Which POs on CFT-4488 are priority for first unload?\n2) Is the quantity on PO 6000445933 final, or should we expect a revised issuing quantity?\n\nOnce confirmed, our dispatch lead will lock appointments and send them back today.\n\nRegards,\nCharger Logistics | CSR Team',
      },
    ],
  },
  {
    id: 'e1',
    from: 'Tania Gonzalez',
    email: 'tania.gonzalez@hisense.com',
    initials: 'TG',
    time: '1:20 PM',
    stamp: 'Jul 28, 2026 at 1:20:52 PM',
    confidence: 100,
    subject: 'CAJA CARGADA 28/JULIO/2026 PO: 413714520 11800VL LOWE\'S DESOTO,TX BULK DC 3PL',
    po: 'PO 413714520',
    ref: '11800VL',
    lane: 'Hisense → Lowe\'s DeSoto, TX',
    dept: 'CSR / Dispatch',
    intent: 'Shipment status update',
    sub: 'Loaded / unloaded confirmation',
    tier: 'Draft',
    reason: 'Acknowledgement',
    body: 'BUEN DÍA\n\nADJUNTO DOCUMENTOS DE CAJA CARGADA 28/JULIO/2026 PO: 413714520 11800VL\n\nSaludos,\nTania',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'Hisense@chargerlogistics.com',
      'tifanny.terreros@chargergloballogistics.com',
      'andrea.santos@chargergloballogistics.com',
      'stephany@chargergloballogistics.com',
      'anmol.duggal@baja-freight.com',
      'anmol.duggal@chargergloballogistics.com',
      'ryan@chargerlogistics.com',
    ],
    ccCount: 21,
    attachments: [
      { name: 'BOL_413714520.pdf', size: '248 KB' },
      { name: 'Packing_List_11800VL.pdf', size: '96 KB' },
    ],
    langs: ['EN', 'ES'],
    tones: [
      {
        id: 'ack',
        label: 'Acknowledge',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la caja cargada del 28/julio/2026, PO 413714520 (11800VL) con destino Lowe\'s DeSoto, TX.\n\nQuedamos al pendiente de cualquier actualización.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the loading documents for 28/July/2026, PO 413714520 (11800VL) heading to Lowe\'s DeSoto, TX.\n\nWe\'ll follow up if anything changes.\n\nThanks,\nCharger Logistics | CSR Team',
      },
      {
        id: 'eta',
        label: 'Acknowledge + ETA',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la caja cargada del 28/julio/2026, PO 413714520 (11800VL).\n\nLa unidad sale hoy de planta; ETA a Lowe\'s DeSoto, TX el 30/julio antes de las 14:00 hrs. Les confirmamos en cuanto cruce.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the loading documents for 28/July/2026, PO 413714520 (11800VL).\n\nThe unit departs today; ETA to Lowe\'s DeSoto, TX is 30/July before 2:00 PM. We\'ll confirm once it crosses.\n\nThanks,\nCharger Logistics | CSR Team',
      },
      {
        id: 'doc',
        label: 'Request missing doc',
        ES: 'Hola Tania,\n\nRecibimos los documentos de la PO 413714520 (11800VL). Nos hace falta el packing list firmado para completar el expediente de cruce.\n\n¿Nos lo puedes enviar hoy? Con eso liberamos la unidad sin demora.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the documents for PO 413714520 (11800VL). We\'re still missing the signed packing list to complete the border file.\n\nCould you send it today? That lets us release the unit without delay.\n\nThanks,\nCharger Logistics | CSR Team',
      },
    ],
  },
  {
    id: 'e2',
    from: 'Tania Gonzalez',
    email: 'tania.gonzalez@hisense.com',
    initials: 'TG',
    time: '1:18 PM',
    stamp: 'Jul 28, 2026 at 1:18:04 PM',
    confidence: 100,
    subject: 'CAJA CARGADA 28/JULIO/2026 PO: 413714519 95950WSA LOWE\'S DESOTO,TX BULK DC 3PL',
    po: 'PO 413714519',
    ref: '95950WSA',
    lane: 'Hisense → Lowe\'s DeSoto, TX',
    dept: 'CSR / Dispatch',
    intent: 'Shipment status update',
    sub: 'Loaded / unloaded confirmation',
    tier: 'Draft',
    reason: 'Acknowledgement',
    body: 'BUEN DÍA\n\nADJUNTO DOCUMENTOS DE CAJA CARGADA 28/JULIO/2026 PO: 413714519 95950WSA',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'Hisense@chargerlogistics.com',
      'ryan@chargerlogistics.com',
    ],
    ccCount: 21,
    attachments: [{ name: 'BOL_413714519.pdf', size: '233 KB' }],
    langs: ['EN', 'ES'],
    tones: [
      {
        id: 'ack',
        label: 'Acknowledge',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la caja cargada del 28/julio/2026, PO 413714519 (95950WSA) con destino Lowe\'s DeSoto, TX.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the loading documents for 28/July/2026, PO 413714519 (95950WSA) heading to Lowe\'s DeSoto, TX.\n\nThanks,\nCharger Logistics | CSR Team',
      },
      {
        id: 'eta',
        label: 'Acknowledge + ETA',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la PO 413714519 (95950WSA). ETA a Lowe\'s DeSoto, TX el 30/julio antes de las 14:00 hrs.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the documents for PO 413714519 (95950WSA). ETA to Lowe\'s DeSoto, TX is 30/July before 2:00 PM.\n\nThanks,\nCharger Logistics | CSR Team',
      },
    ],
  },
  {
    id: 'e3',
    from: 'Tania Gonzalez',
    email: 'tania.gonzalez@hisense.com',
    initials: 'TG',
    time: '1:11 PM',
    stamp: 'Jul 28, 2026 at 1:11:39 PM',
    confidence: 98,
    subject: 'CAJA CARGADA 28/JULIO/2026 PO: 413714526 14264WLA Lowe\'s DC 3368',
    po: 'PO 413714526',
    ref: '14264WLA',
    lane: 'Hisense → Lowe\'s DC 3368',
    dept: 'CSR / Dispatch',
    intent: 'Shipment status update',
    sub: 'Loaded / unloaded confirmation',
    tier: 'Draft',
    reason: 'Acknowledgement',
    body: 'BUEN DÍA\n\nADJUNTO DOCUMENTOS DE CAJA CARGADA 28/JULIO/2026 PO: 413714526 14264WLA\n\nEste va a DC 3368, favor de confirmar cita.',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'Hisense@chargerlogistics.com',
    ],
    ccCount: 18,
    attachments: [{ name: 'BOL_413714526.pdf', size: '251 KB' }],
    langs: ['EN', 'ES'],
    tones: [
      {
        id: 'ack',
        label: 'Acknowledge + appointment',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la PO 413714526 (14264WLA) para Lowe\'s DC 3368.\n\nEstamos gestionando la cita de descarga y te confirmamos el número en cuanto el DC lo asigne.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the documents for PO 413714526 (14264WLA) to Lowe\'s DC 3368.\n\nWe\'re booking the unload appointment and will send you the confirmation number as soon as the DC assigns it.\n\nThanks,\nCharger Logistics | CSR Team',
      },
      {
        id: 'ack2',
        label: 'Acknowledge only',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la PO 413714526 (14264WLA). Gracias.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the documents for PO 413714526 (14264WLA). Thank you.\n\nThanks,\nCharger Logistics | CSR Team',
      },
    ],
  },
  {
    id: 'e4',
    from: 'Yumei Wang',
    email: 'yumei.wang@partners.hisense.com',
    initials: 'YW',
    time: '11:47 AM',
    stamp: 'Jul 28, 2026 at 11:47:12 AM',
    confidence: 62,
    subject: 'Re: EXT: Top Urgent Reconstruction Of June Customs Data — Need to update',
    po: 'June 2026',
    ref: 'ACE/ACI',
    lane: 'Customs — cross-border filings',
    dept: 'Customs / Compliance',
    intent: 'Documentation correction',
    sub: 'Multi-intent · needs review',
    tier: 'Review',
    reason: 'Low confidence · multi-intent',
    body: 'Hello team,\n\nPlease update the June customs filing data as soon as possible. We found mismatches on 14 entries between the manifest and the ACE filing for June. Please advise which reference is authoritative and confirm when the corrected set will be resubmitted.\n\nAlso, who is the new contact after Andrea\'s handover?\n\nThanks,\nYumei',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'customs@chargerlogistics.com',
      'ryan@chargerlogistics.com',
    ],
    ccCount: 9,
    attachments: [{ name: 'June_Entry_Variance.xlsx', size: '1.2 MB' }],
    langs: ['EN'],
    tones: [
      {
        id: 'hold',
        label: 'Acknowledge + escalate',
        EN: 'Hi Yumei,\n\nThanks for flagging this. We\'re reviewing the 14 variances in your file against our June ACE submissions now.\n\nOur customs lead will come back to you by end of day tomorrow with the authoritative reference and a resubmission date. Brenda Munguia is your contact following Andrea\'s handover.\n\nRegards,\nCharger Logistics | Customs',
      },
      {
        id: 'ask',
        label: 'Request specifics',
        EN: 'Hi Yumei,\n\nBefore we correct the June set, could you confirm which 14 entry numbers are affected and whether the variance is on quantity, value, or HS classification?\n\nThat lets us amend in one filing rather than several.\n\nRegards,\nCharger Logistics | Customs',
      },
    ],
  },
  {
    id: 'e5',
    from: 'Tania Gonzalez',
    email: 'tania.gonzalez@hisense.com',
    initials: 'TG',
    time: 'Yesterday',
    stamp: 'Jul 27, 2026 at 5:02:18 PM',
    confidence: 100,
    subject: 'CAJA CARGADA 27/JULIO/2026 PO: 6000445241 97971MSM PANTOS-TX-FG',
    po: 'PO 6000445241',
    ref: '97971MSM',
    lane: 'Hisense → Pantos, TX',
    dept: 'CSR / Dispatch',
    intent: 'Shipment status update',
    sub: 'Loaded / unloaded confirmation',
    tier: 'Draft',
    reason: 'Acknowledgement',
    body: 'BUEN DÍA\n\nADJUNTO DOCUMENTOS DE CAJA CARGADA 27/JULIO/2026 PO: 6000445241 97971MSM',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'Hisense@chargerlogistics.com',
    ],
    ccCount: 20,
    attachments: [{ name: 'BOL_6000445241.pdf', size: '219 KB' }],
    langs: ['EN', 'ES'],
    tones: [
      {
        id: 'ack',
        label: 'Acknowledge',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la caja cargada del 27/julio/2026, PO 6000445241 (97971MSM) para Pantos, TX.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the loading documents for 27/July/2026, PO 6000445241 (97971MSM) to Pantos, TX.\n\nThanks,\nCharger Logistics | CSR Team',
      },
    ],
  },
  {
    id: 'e6',
    from: 'Tania Gonzalez',
    email: 'tania.gonzalez@hisense.com',
    initials: 'TG',
    time: 'Yesterday',
    stamp: 'Jul 27, 2026 at 4:58:44 PM',
    confidence: 99,
    subject: 'CAJA CARGADA 27/JULIO/2026 PO: 6000445214 10757MSM PANTOS-TX-FG',
    po: 'PO 6000445214',
    ref: '10757MSM',
    lane: 'Hisense → Pantos, TX',
    dept: 'CSR / Dispatch',
    intent: 'Shipment status update',
    sub: 'Loaded / unloaded confirmation',
    tier: 'Draft',
    reason: 'Acknowledgement',
    body: 'BUEN DÍA\n\nADJUNTO DOCUMENTOS DE CAJA CARGADA 27/JULIO/2026 PO: 6000445214 10757MSM',
    to: [
      'brenda.munguia@chargergloballogistics.com',
      'Hisense@chargerlogistics.com',
    ],
    ccCount: 20,
    attachments: [{ name: 'BOL_6000445214.pdf', size: '204 KB' }],
    langs: ['EN', 'ES'],
    tones: [
      {
        id: 'ack',
        label: 'Acknowledge',
        ES: 'Hola Tania,\n\nRecibimos la documentación de la caja cargada del 27/julio/2026, PO 6000445214 (10757MSM) para Pantos, TX.\n\nSaludos,\nCharger Logistics | Equipo CSR',
        EN: 'Hi Tania,\n\nWe\'ve received the loading documents for 27/July/2026, PO 6000445214 (10757MSM) to Pantos, TX.\n\nThanks,\nCharger Logistics | CSR Team',
      },
    ],
  },
]

export const TIERS = ['All tiers', 'Draft', 'Review', 'Escalation', 'Manual']
export const INTENTS = [
  'All intents',
  'Shipment status update',
  'Documentation correction',
  'Rate request',
]
export const AUTO_OK = 98
